# Generated by Django 4.1.4 on 2023-01-04 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Бренд')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренд',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Категория')),
                ('slug', models.SlugField(max_length=255, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категория',
            },
        ),
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Графический процессор')),
            ],
            options={
                'verbose_name': 'Графический процессор',
                'verbose_name_plural': 'Графический процессор',
            },
        ),
        migrations.CreateModel(
            name='ManufacturerGPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Производитель ГП')),
            ],
            options={
                'verbose_name': 'Производитель ГП',
                'verbose_name_plural': 'Производитель ГП',
            },
        ),
        migrations.CreateModel(
            name='MemoryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Тип памяти')),
            ],
            options={
                'verbose_name': 'Тип памяти',
                'verbose_name_plural': 'Тип памяти',
            },
        ),
        migrations.CreateModel(
            name='PowerConnector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Разъем питания')),
            ],
            options={
                'verbose_name': 'Разъем питания',
                'verbose_name_plural': 'Разъем питания',
            },
        ),
        migrations.CreateModel(
            name='VideoConnector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Видеоразъем')),
            ],
            options={
                'verbose_name': 'Видеоразъем',
                'verbose_name_plural': 'Видеоразъем',
            },
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=20, verbose_name='Видеокарта')),
                ('slug', models.SlugField(max_length=255, verbose_name='URL')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
                ('video_memory_capacity', models.IntegerField(default=0, verbose_name='Объем видеопамяти')),
                ('frequency_GPU', models.IntegerField(default=0, verbose_name='Частота ГП')),
                ('video_card_length', models.IntegerField(default=0, verbose_name='Длина')),
                ('discount', models.BooleanField(verbose_name='Акция')),
                ('new', models.BooleanField(verbose_name='Новинка')),
                ('GPU', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Catalog.gpu', verbose_name='Графический процессор')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Catalog.brand', verbose_name='Бренд')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Catalog.category', verbose_name='Категория')),
                ('manufacturer_GPU', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Catalog.manufacturergpu', verbose_name='Производитель ГП')),
                ('memory_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Catalog.memorytype', verbose_name='Тип памяти')),
                ('power_connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Catalog.powerconnector', verbose_name='Разъем питания')),
                ('video_connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Catalog.videoconnector', verbose_name='Видеоразъем')),
            ],
            options={
                'verbose_name': ' КАТАЛОГ',
                'verbose_name_plural': ' КАТАЛОГ',
            },
        ),
    ]
