# Generated by Django 4.1.4 on 2023-01-20 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категория',
            },
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50, verbose_name='Видеокарта')),
                ('GPU', models.CharField(max_length=50, verbose_name='Графический процессор')),
                ('manufacturer_GPU', models.CharField(max_length=50, verbose_name='Производитель ГП')),
                ('memory_type', models.CharField(max_length=50, verbose_name='Тип памяти')),
                ('power_connector', models.CharField(max_length=50, verbose_name='Разъем питания')),
                ('video_connector', models.CharField(max_length=50, verbose_name='Видеоразъем')),
                ('price', models.PositiveBigIntegerField(default=0, verbose_name='Цена')),
                ('brand', models.CharField(max_length=50, verbose_name='Бренд')),
                ('video_memory_capacity', models.IntegerField(default=0, verbose_name='Объем видеопамяти')),
                ('frequency_GPU', models.IntegerField(default=0, verbose_name='Частота ГП')),
                ('video_card_length', models.IntegerField(default=0, verbose_name='Длина')),
                ('discount', models.BooleanField(verbose_name='Акция')),
                ('new', models.BooleanField(verbose_name='Новинка')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Catalog.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': ' КАТАЛОГ',
                'verbose_name_plural': ' КАТАЛОГ',
            },
        ),
    ]
