# Generated by Django 4.1.4 on 2023-01-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalog',
            name='slug',
        ),
        migrations.AlterField(
            model_name='catalog',
            name='GPU',
            field=models.CharField(max_length=55, verbose_name='Графический процессор'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='brand',
            field=models.CharField(max_length=50, verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='manufacturer_GPU',
            field=models.CharField(max_length=20, verbose_name='Производитель ГП'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='memory_type',
            field=models.CharField(max_length=20, verbose_name='Тип памяти'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='power_connector',
            field=models.CharField(max_length=20, verbose_name='Разъем питания'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='video_connector',
            field=models.CharField(max_length=20, verbose_name='Видеоразъем'),
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='GPU',
        ),
        migrations.DeleteModel(
            name='ManufacturerGPU',
        ),
        migrations.DeleteModel(
            name='MemoryType',
        ),
        migrations.DeleteModel(
            name='PowerConnector',
        ),
        migrations.DeleteModel(
            name='VideoConnector',
        ),
    ]
