# Generated by Django 4.1.4 on 2023-01-11 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog', '0003_remove_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='GPU',
            field=models.CharField(max_length=50, verbose_name='Графический процессор'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='manufacturer_GPU',
            field=models.CharField(max_length=50, verbose_name='Производитель ГП'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='memory_type',
            field=models.CharField(max_length=50, verbose_name='Тип памяти'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='power_connector',
            field=models.CharField(max_length=50, verbose_name='Разъем питания'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='price',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='product_name',
            field=models.CharField(max_length=50, verbose_name='Видеокарта'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='video_connector',
            field=models.CharField(max_length=50, verbose_name='Видеоразъем'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Категория'),
        ),
    ]
