# Generated by Django 4.1.4 on 2023-01-03 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Фамилия и имя')),
                ('email', models.CharField(max_length=50, verbose_name='Электронная почта')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер для связи')),
                ('home_address', models.CharField(max_length=150, verbose_name='Адрес доставки')),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
