# Generated by Django 4.1.4 on 2023-01-05 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_alter_userprofile_options_remove_userprofile_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='home_address',
            field=models.CharField(default=1, max_length=150, verbose_name='Адрес доставки'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(default=1, max_length=20, verbose_name='Номер для связи'),
        ),
    ]
